version: '3'
services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rails_project_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:latest

volumes:
  db-data:
    driver: local