version: '3'

services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql2://user:password@db/rails_app_development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rails_app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  redis:
    image: redis:latest